# Generated by Django 5.0.3 on 2024-03-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Amount', models.CharField(max_length=20)),
                ('Payment_id', models.CharField(max_length=100)),
                ('Paid', models.BooleanField(default=False)),
            ],
        ),
    ]
